export const dataVehicle = [
  {
    name: 'Chevrolet Silverado 1500',
    price: '$29,415',
    description: 'In a pickup market gone fancy, the Silverado sticks to its basic-truck recipe. The steering is accurate, and the Silverado handles more like a big car than a big truck.',
    distance: '31,730 KM',
    year: '2015',
    condition: 'Used',
    speed: '8',
    transmission: 'Automatic',
    fuel: 'Petrol',
    type: 'PREMIUM',
    image: '../../media/270x230/dodge.jpg'
  },
  {
    name: '2015 Ferrari LaFerrari',
    price: '$1,420,112',
    description: 'Above sports cars, there are exotic sports cars. And the LaFerrari is poised to be the king of all exotic sports cars. Its 789-hp V-12 gets a 161-hp boost from an electric motor',
    distance: '35,000 KM',
    year: '2015',
    condition: 'Used',
    speed: '7',
    transmission: 'Automatic',
    fuel: 'Petrol',
    type: 'LEASING AVAILABLE',
    image: '../../media/270x230/ferrari.jpg'
  },
  {
    name: 'Jaguar XF 2015',
    price: '$51,170',
    description: 'With curvy lines, gorgeous wood, and leather interiors—and performance—the XF combines all there is to love about Jaguars. The 240-hp, 2.0-liter turbocharged',
    distance: '0,000 KM',
    year: '2015',
    condition: 'Used',
    speed: '8',
    transmission: 'Automatic',
    fuel: 'Petrol',
    type: 'NEW LISTING',
    image: '../../media/270x230/jaguarList.jpg'
  },
  {
    name: 'Lexus LS460 F Sport',
    price: '$73,445',
    description: 'The LS was the first Japanese car to mix European luxury with vaunted Japanese reliability, and it continues offering that compelling combination today',
    distance: '35,000 KM',
    year: '2015',
    condition: 'Used',
    speed: '8',
    transmission: 'Automatic',
    fuel: 'Petrol',
    type: '1 OWNER',
    image: '../../media/270x230/lexus.jpg'
  },
  {
    name: 'Mercedes-Benz GL63 AMG',
    price: '$120,375',
    description: 'The top-flight GL63 AMG is built for those who crave performance, luxury, and exclusivity — you know; the finer things in life. AMG works its magic on the GL',
    distance: '35,000 KM',
    year: '2015',
    condition: 'Used',
    speed: '7',
    transmission: 'Automatic',
    fuel: 'Petrol',
    type: '',
    image: '../../media/270x230/mersAmg.jpg'
  },
  {
    name: '2016 Nissan Maxima',
    price: '$32,115',
    description: 'Once billed as the "four-door sports car," the Maxima has grown bigger and heavier over the decades, detracting from its appeal. The current generation',
    distance: '35,000 KM',
    year: '2015',
    condition: 'Used',
    speed: '7',
    transmission: 'Automatic',
    fuel: 'Petrol',
    type: '',
    image: '../../media/270x230/nissanList.jpg'
  },
];